export enum AppRoutes {
  Home = "/",
  Sigin = "/signin",
  Signup = "/signup",
  Courses = "/courses",
  Course = "/courses/:courseId",
  Lesson = "/courses/:courseId/:lessonId",
  Test = "/tests/:courseId/:testId",
  LeaderBoard = "/leader-board",
  Events = "/events",
  Profile = "/profile",
  Certificate = "/certificate/:courseId",
  Admin = "/admin",
  All = "*",
}
